services:
  postgres:
    image: postgres
    container_name: my-kitchen-database
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: my-kitchen-backend
    env_file: .env
    depends_on:
      - postgres
    networks:
      - my-network
    ports:
      - "8080:8080"
    command: >
      sh -c "
             java -cp classes:dependency/* org.example.db.TestConnect &&
             java -cp classes:dependency/* org.example.db.DataLoader &&
             java -cp classes:dependency/* org.example.db.SqlFileExecutor &&
             java -jar app.jar"

networks:
  my-network:
