services:
  postgres:
    image: postgres
    container_name: my-kitchen-database
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - my-network

  backend:
    image: ${vars.DOCKER_USERNAME}/qqb-kitchen-backend:${TAG}
    container_name: my-kitchen-backend
    env_file: .env
    depends_on:
      - postgres
    networks:
      - my-network
    ports:
      - "8080:8080"

  frontend:
    image: ${vars.DOCKER_USERNAME}/qqb-kitchen-backend:${TAG}
    container_name: my-kitchen-frontend
    env_file: .env
    depends_on:
      - backend
    networks:
      - my-network
    ports:
      - "3000:3000"

networks:
  my-network:
