services:
  postgres:
    image: postgres
    container_name: my-kitchen-database
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: my-kitchen-backend
    env_file: .env
    depends_on:
      - postgres
    networks:
      - my-network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: my-kitchen-frontend
    env_file: .env
    depends_on:
      - backend
    networks:
      - my-network
    ports:
      - "80:80"

networks:
  my-network:
