name: CD Pipeline for EC2 with Docker Compose

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Backend Docker image tag
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-backend
          tags: |
            type=sha

      - name: Extract Frontend Docker image tag
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-frontend
          tags: |
            type=sha

      - name: Substitute env variables in docker compose file before scp
        run: |
          envsubst < docker-compose.yml > docker-compose.tmp
          mv docker-compose.tmp docker-compose.yml
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKER_USERNAME }}
          BACKEND_TAG: ${{ steps.meta-backend.outputs.version }}
          FRONTEND_TAG: ${{ steps.meta-frontend.outputs.version }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          USER: ${{ secrets.EC2_USER }}
          ENV: ${{ secrets.ENV_FILE}}
          DOCKERHUB_USER: ${{ vars.DOCKER_USERNAME }}
          DOCKERHUB_PASS: ${{ secrets.DOCKER_PASSWORD }}
          DDNS_SCRIPT: ${{ secrets.UPDATE_DDNS }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          echo "$DDNS_SCRIPT" | base64 -d > ddns_script.py
          scp -o StrictHostKeyChecking=no -i private_key ddns_script.py ${USER}@${HOST}:/home/ubuntu/ddns_script.py
          scp -o StrictHostKeyChecking=no -i private_key docker-compose.yml ${USER}@${HOST}:/home/ubuntu/docker-compose.yml
          scp -o StrictHostKeyChecking=no -i private_key scripts/shell/docker-rebuild.sh ${USER}@${HOST}:/home/ubuntu/docker-rebuild.sh
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} << EOF
            echo "$ENV" > /home/ubuntu/.env
            chmod 600 /home/ubuntu/.env
        
            chmod +x /home/ubuntu/ddns_script.py
            pip3 install boto3 python-dotenv
            sudo bash -c 'cat > /etc/systemd/system/ddns.service << EOL
          [Unit]
          Description=Dynamic DNS Updater
          After=network.target
          
          [Service]
          ExecStart=/usr/bin/python3 /home/ubuntu/ddns_script.py
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOL'
             
            # Create Docker service for auto-restart
            sudo bash -c 'cat > /etc/systemd/system/docker-compose.service << EOL
          [Unit]
          Description=Docker Compose
          Requires=docker.service
          After=docker.service network.target
          
          [Service]
          ExecStart=/home/ubuntu/docker-rebuild.sh
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOL'
          
            # Enable two services
            sudo systemctl daemon-reload
            sudo systemctl enable ddns.service docker-compose.service
            sudo systemctl start ddns.service 
            
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            chmod +x /home/ubuntu/docker-rebuild.sh
            /home/ubuntu/docker-rebuild.sh
          EOF
          rm -f private_key
