name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Tag variable
        run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Add .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker images metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-backend
            ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-frontend
          tags: |
            type=ref, event=branch
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-backend:${{ env.TAG }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-frontend:${{ env.TAG }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
