name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Add CSV files
        run: |
          mkdir csv-files
          echo "${{ secrets.CSV_CATEGORIES }}" | base64 -d > csv-files/categories.csv
          echo "${{ secrets.CSV_INGREDIENTS }}" | base64 -d > csv-files/ingredients.csv
          echo "${{ secrets.CSV_RECIPES_INGREDIENTS }}" | base64 -d > csv-files/recipes_ingredients.csv
          echo "${{ secrets.CSV_RECIPES }}" | base64 -d > csv-files/recipes.csv
          echo "${{ secrets.CSV_RECIPES_INSTRUCTIONS }}" | base64 -d > csv-files/recipes_instructions.csv          
          echo "${{ secrets.CSV_RECIPES_TAGS }}" | base64 -d > csv-files/recipes_tags.csv
          echo "${{ secrets.CSV_TYPES }}" | base64 -d > csv-files/types.csv
          echo "${{ secrets.CSV_TAGS }}" | base64 -d > csv-files/tags.csv

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run the JS script to download images and update recipes CSV image column
        run: node scripts/javascript/process_images.js

      - name: Verify the images directory exists and contains files
        run: |
          echo "Checking contents of src/main/resources/recipes-images/"
          ls -l src/main/resources/recipes-images/

      - name: Upload recipe images
        uses: actions/upload-artifact@v4
        with:
          name: recipe-images
          path: src/main/resources/recipes-images/
          retention-days: 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker Backend image metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-backend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Extract Docker Frontend image metadata
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/qqb-kitchen-frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-backend.outputs.tags }}
          annotations: ${{ steps.meta-backend.outputs.annotations }}
          provenance: true
          sbom: true

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-frontend.outputs.tags }}
          annotations: ${{ steps.meta-frontend.outputs.annotations }}
          provenance: true
          sbom: true
